Repository Fondus/PI-Adapter, pull requests merged in 2018-10, with the labels that each got.

#14 Update with the unnecessary dependency.
  PI-Adapter-NCHC-RainRunoff/src/main/java/tw/fondus/fews/adapter/pi/runoff/nchc/RainRunoffPreAdapter.java
  PI-Adapter-SensLink2/src/main/java/tw/fondus/fews/adapter/pi/senslink2/ExportToSensLinkAdapter.java
  PI-Adapter-SensLink2/src/main/java/tw/fondus/fews/adapter/pi/senslink2/ImportFromSensLinkAdapter.java
  PI-Adapter-SensLink2/src/main/java/tw/fondus/fews/adapter/pi/senslink2/util/AdapterUtils.java
  PI-Adapter-SensLink2/src/main/java/tw/fondus/fews/adapter/pi/senslink2/util/RunArguments.java
  PI-Adapter-SensLink2/src/test/java/tw/fondus/fews/adapter/pi/senslink2/ExportToSensLinkAdapterTest.java
  PI-Adapter-SensLink2/src/test/java/tw/fondus/fews/adapter/pi/senslink2/ImportFromSensLinkAdapterTest.java
  pom.xml
Labels: Type: Dependency update, Type: Enhancement Improve

#15 First version of Pi-Adapter for NCHC RTC model.
  PI-Adapter-NCHC-RTC-2D/pom.xml
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCExecutable.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCPreAdapter.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCPreprocessExecutable.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/util/ContentBuilder.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/util/FileUtils.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/util/PreAdapterArguments.java
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/util/RunArguments.java
  PI-Adapter-NCHC-RTC-2D/src/test/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCExecutableTest.java
  PI-Adapter-NCHC-RTC-2D/src/test/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCPreAdapterTest.java
  PI-Adapter-NCHC-RTC-2D/src/test/java/tw/fondus/fews/adapter/pi/rtc/nchc/RTCPreprocessExecutableTest.java
Labels: Type: Feature

#16 Fixed comment of FileUtils note.
  PI-Adapter-NCHC-RTC-2D/pom.xml
  PI-Adapter-NCHC-RTC-2D/src/main/java/tw/fondus/fews/adapter/pi/rtc/nchc/util/FileUtils.java
  pom.xml
Labels: Type: Cleanup
