Repository Fondus/PI-Adapter, pull requests merged in 2019-01, with the labels that each got.

#21 Update Senslink 3.0 and Disaster loss.
  PI-Adapter-API-RiChi-Disaster-Loss/src/main/java/tw/fondus/fews/adapter/pi/loss/richi/DisasterLossAdapter.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/main/java/tw/fondus/fews/adapter/pi/loss/richi/util/DisasterLossProperties.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/main/java/tw/fondus/fews/adapter/pi/loss/richi/util/DisasterLossUtils.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/main/java/tw/fondus/fews/adapter/pi/loss/richi/util/Parameter.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/main/java/tw/fondus/fews/adapter/pi/loss/richi/xml/Loss.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/test/java/tw/fondus/fews/adapter/pi/loss/richi/util/DisasterLossPropertiesTest.java
  PI-Adapter-API-RiChi-Disaster-Loss/src/test/resources/example-disasterloss.properties
  PI-Adapter-SensLink/src/main/java/tw/fondus/fews/adapter/pi/senslink/v3/ImportFromSensLinkAdapter.java
  PI-Adapter-SensLink/src/test/java/tw/fondus/fews/adapter/pi/senslink/v3/ImportFromSensLinkAdapterTest.java
  pom.xml
Labels: Type: Enhancement Improve

#22 Update the dependencies.
  PI-Adapter-NCHC-RainRunoff/pom.xml
  pom.xml
Labels: Type: Dependency update

#24 The first version of PI-Adapter-NCHC-LongTimeFlow.
  PI-Adapter-NCHC-LongTimeFlow/pom.xml
  PI-Adapter-NCHC-LongTimeFlow/src/main/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFExecutable.java
  PI-Adapter-NCHC-LongTimeFlow/src/main/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFPostAdapter.java
  PI-Adapter-NCHC-LongTimeFlow/src/main/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFPreAdapter.java
  PI-Adapter-NCHC-LongTimeFlow/src/main/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/util/RunArguments.java
  PI-Adapter-NCHC-LongTimeFlow/src/test/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFExecutableTest.java
  PI-Adapter-NCHC-LongTimeFlow/src/test/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFPostAdapterTest.java
  PI-Adapter-NCHC-LongTimeFlow/src/test/java/tw/fondus/fews/adapter/pi/flow/longtime/nchc/LTFPreAdapterTest.java
  pom.xml
Labels: Type: Feature
